name: Run Python Script

on: 
  push:
    branches: 
      - main

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.6'  # Substitua '3.x' pela versão específica, se necessário

      - name: Install dependencies
        run: pip install -r requirements.txt  # Instala as dependências do requirements.txt

      - name: Run Python script
        run: python telegram_bot.py  # Substitua pelo nome do seu script Python
