from telethon import TelegramClient, events
import re
import schedule
import time

# Coloque suas credenciais da API do Telegram aqui
api_id = '27555772'
api_hash = '9434e8bd894dbe4c2fb431003e5dbe9b'
phone = '+5573999175769'

# O link de afiliado que você deseja colocar
meu_link_afiliado = 'https://www.homebroker.com/pt'

# Nome de usuário ou ID do canal de origem (onde as mensagens serão copiadas)
canal_origem = '1002228938682'
# Nome de usuário ou ID do canal/destinatário onde você quer reenviar a mensagem
canal_destino = '1002190831140'

# Inicializa o cliente do Telegram
client = TelegramClient('session_name', api_id, api_hash)

# Função para modificar o link de afiliado na mensagem
def modificar_mensagem(texto):
    texto_modificado = re.sub(r'https?://\S+', f'📊 [Clique aqui para abrir a corretora]({meu_link_afiliado})', texto)
    return texto_modificado

async def fetch_and_forward_messages():
    # Captura as mensagens e processa
    async for message in client.iter_messages(canal_origem):
        if message.video or message.sticker:  # Ignora vídeos e figurinhas
            continue

        mensagem_original = message.message
        mensagem_modificada = modificar_mensagem(mensagem_original)
        await client.send_message(canal_destino, mensagem_modificada, parse_mode='md')

# Agendar a função para ser executada a cada 5 minutos
schedule.every(5).minutes.do(fetch_and_forward_messages)

async def job():
    while True:
        schedule.run_pending()
        await asyncio.sleep(1)  # Pausa para evitar uso excessivo de CPU

# Inicia o cliente
with client:
    client.loop.run_until_complete(job())
